---
abstract: 'Test your regular expressions'
author:
  - 'Abigail <test-regexp@abigail.be>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  Test::Tester: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  Test::Tester: 0
  strict: 0
  warnings: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120630'
keywords:
  - 'regular expression'
  - pattern
  - regexp
  - test
  - tests
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Regexp
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  Hash::Util::FieldHash: 0
  Test::Builder: 0
  perl: 5.01
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Abigail/Test-Regexp.git
version: 2014052301
x_test_requires:
  Test::More: 0.88
  Test::Tester: 0
  strict: 0
  warnings: 0
